---
- name: Deploy Nillion Verifier Node using Ansible
  hosts: all
  become: true

  vars:
    NODE_NAME: nillion-verifier
    NODE_DIR: "/root/nillion/accuser"
    DOCKER_IMAGE: "nillion/retailtoken-accuser:v1.0.1"
    RPC_ENDPOINT: "https://testnet-nillion-rpc.lavenderfive.com"
    BLOCK_START: "5392038"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Verify Docker installation
      command: docker --version
      register: docker_version
      ignore_errors: yes

    - name: Install Docker if not present
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        sudo apt-get update
        sudo apt-get install -y docker-ce
      when: docker_version.rc != 0

    - name: Create a directory for node data
      file:
        path: "{{ NODE_DIR }}"
        state: directory
        mode: '0755'

    - name: Pull Nillion Docker image
      docker_image:
        name: "{{ DOCKER_IMAGE }}"
        source: pull

    - name: Initialize the Nillion verifier
      command: docker run -v {{ NODE_DIR }}:/var/tmp {{ DOCKER_IMAGE }} initialise
      args:
        creates: "{{ NODE_DIR }}/credentials.json"

    - name: Display critical information and next steps
      debug:
        msg: |
          IMPORTANT NEXT STEPS:
          1. Ensure you have a Keplr wallet funded with NIL tokens from the Nillion faucet.
          2. Your Nillion node address is stored in {{ NODE_DIR }}/credentials.json. Please fund this address using the Nillion faucet.
          3. Register your node on the Nillion portal (https://verifier.nillion.com/) using your Keplr wallet for authentication.
          4. Use the account_id and public_key from {{ NODE_DIR }}/credentials.json to complete the registration.
          5. Wait 30-60 minutes after registration before starting the node service.
          6. After waiting, start the service manually with: sudo systemctl start nillion-verifier-node

    - name: Enable Nillion Verifier Node service (do not start immediately)
      systemd:
        name: nillion-verifier-node
        enabled: yes
        state: stopped
    - name: Create a systemd service file for Nillion Verifier Node
      template:
        src: templates/nillion-verifier-node.service.j2
        dest: /etc/systemd/system/nillion-verifier-node.service
      vars:
        node_dir: "{{ NODE_DIR }}"
        docker_image: "{{ DOCKER_IMAGE }}"
        rpc_endpoint: "{{ RPC_ENDPOINT }}"
        block_start: "{{ BLOCK_START }}"

    - name: Reload systemd daemon
      systemd:
        daemon_reload: true

    - name: Enable Nillion Verifier Node service
      systemd:
        name: nillion-verifier-node
        enabled: true
        state: stopped